feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: phoenix2014 #CSL-Daily, phoenix2014-T, phoenix2014, CSL
num_epoch: 150
work_dir: ./work_dir/test/
batch_size: 4
random_seed: 0
test_batch_size: 4
num_worker: 10
device: 0
log_interval: 10000
eval_interval: 1
save_interval: 5
# python in default
evaluate_tool: sclite  # sclite or python
loss_weights:
  SeqCTC: 1.0
  ConvCTC: 1.0
  Dist: 25.0
  Cu: 0.0005
  Cp: 0.0005
# load_weights: ''

optimizer_args:
  optimizer: Adam # Adam, AdamW
  base_lr: 0.0001
  step: [40, 60]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False
  max_epoch: 80
  warmup_epoch: 5

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0  # 0-1 represents ratio, >1 represents absolute value
  input_size: 224

model: slr_network.SLRModel
decode_mode: beam
model_args:
  num_classes: 1296
  c2d_type: resnet34 # resnet18 resnet34
  conv_type: 2
  use_bn: 1
  # SMKD
  share_classifier: True
  weight_norm: True